package com.jy.mybatis;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERID
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERNAME
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERADDR
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    private String useraddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERID
     *
     * @return the value of USERINFO.USERID
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERID
     *
     * @param userid the value for USERINFO.USERID
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERNAME
     *
     * @return the value of USERINFO.USERNAME
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERNAME
     *
     * @param username the value for USERINFO.USERNAME
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERADDR
     *
     * @return the value of USERINFO.USERADDR
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public String getUseraddr() {
        return useraddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERADDR
     *
     * @param useraddr the value for USERINFO.USERADDR
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    public void setUseraddr(String useraddr) {
        this.useraddr = useraddr == null ? null : useraddr.trim();
    }
}