package com.jy.mybatis;

import com.jy.mybatis.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Tue May 05 23:31:10 CST 2020
     */
    int insertSelective(Userinfo record);
}