package com.jy.mappers;

import com.jy.learnMybatis.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    int insertSelective(Userinfo record);
    
    /*
    @param id
    @return 
    */
    Userinfo selectById(Long id);
}