server:
  port: 8081
spring:
  application:
    name: server01
  #数据源配置
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.99.100:1521:XE
    username: yyq
    password: yyq
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: false
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

  mybatis:
    # spring boot集成mybatis的方式打印sql
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
