package com.jy.mybatis;

import com.jy.mybatis.Userinfo;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    int insertSelective(Userinfo record);
}