package com.jy.mybatis;

public class Userinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERID
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERNAME
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERADD
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    private String useradd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERID
     *
     * @return the value of USERINFO.USERID
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERID
     *
     * @param userid the value for USERINFO.USERID
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERNAME
     *
     * @return the value of USERINFO.USERNAME
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERNAME
     *
     * @param username the value for USERINFO.USERNAME
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERADD
     *
     * @return the value of USERINFO.USERADD
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public String getUseradd() {
        return useradd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERADD
     *
     * @param useradd the value for USERINFO.USERADD
     *
     * @mbggenerated Sat May 02 10:33:38 GMT+08:00 2020
     */
    public void setUseradd(String useradd) {
        this.useradd = useradd == null ? null : useradd.trim();
    }
}