package org.example.pojo;

import org.apache.ibatis.plugin.Intercepts;

public class Tmpuserinfo2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMPUSERINFO2.USERNAME
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMPUSERINFO2.AGE
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TMPUSERINFO2.ADDR
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMPUSERINFO2.USERNAME
     *
     * @return the value of TMPUSERINFO2.USERNAME
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMPUSERINFO2.USERNAME
     *
     * @param username the value for TMPUSERINFO2.USERNAME
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMPUSERINFO2.AGE
     *
     * @return the value of TMPUSERINFO2.AGE
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMPUSERINFO2.AGE
     *
     * @param age the value for TMPUSERINFO2.AGE
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TMPUSERINFO2.ADDR
     *
     * @return the value of TMPUSERINFO2.ADDR
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TMPUSERINFO2.ADDR
     *
     * @param addr the value for TMPUSERINFO2.ADDR
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}