package org.example.pojo;

public interface Tmpuserinfo2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMPUSERINFO2
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    int insert(Tmpuserinfo2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TMPUSERINFO2
     *
     * @mbggenerated Sun Jan 24 17:53:37 GMT+08:00 2021
     */
    int insertSelective(Tmpuserinfo2 record);
}