management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8082
spring:
  application:
    name: server01
  #数据源配置
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@168.10.49.181:1521:etcwbdevdb2
    username: obudev
    password: obudev
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: false
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

  mybatis:
    # spring boot集成mybatis的方式打印sql
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



eureka:
  instance:
    prefer-ip-address: true
    hostname: 192.168.1.6
    ip-address: 192.168.1.6
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://168.10.49.181:8000/eureka/

com:
  zipkin:
    serviceName: server01
    url: http://192.168.1.7:9411
    connectTimeout: 6000
    readTimeout: 6000
    flushInterval: 1
    compressionEnabled: true


